package com.interior.platform.realtime.domain;

public enum RealtimeEventType {
    NOTIFICATION_CREATED,
    NOTIFICATION_READ,
    NOTIFICATIONS_READ_ALL,
    LEAD_CREATED,
    LEAD_UPDATED,
    AI_JOB_QUEUED,
    AI_JOB_PROCESSING,
    AI_JOB_COMPLETED,
    AI_JOB_FAILED,
    REVIEW_RECEIVED,
    REVIEW_RESPONSE_UPDATED,
    CLIENT_CONCEPT_APPROVED,
    CLIENT_CONCEPT_CHANGES_REQUESTED,
    CLIENT_COMMENT_ADDED,
    CLIENT_REVISION_SHARED,
    VERIFICATION_STATUS_CHANGED,
    STUDIO_INVITATION_CREATED,
    STUDIO_INVITATION_ACCEPTED,
    STUDIO_MEMBER_ADDED,
    STUDIO_MEMBER_ROLE_CHANGED,
    STUDIO_MEMBER_REMOVED,
    SYSTEM_NOTICE,
    RESYNC,
    HEARTBEAT
}
