import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Check, ShieldCheck, MessageSquare } from 'lucide-react';
import { EditorialProjects } from './EditorialProjects';
import styles from './EditorialHome.module.css';

const categories = [
  { name: 'Modular kitchens', slug: 'modular-kitchens', image: 'kitchen', note: 'The heart of the home' },
  { name: 'Wardrobes & storage', slug: 'wardrobes', image: 'wardrobe', note: 'Every inch, considered' },
  { name: 'TV & living units', slug: 'tv-units', image: 'tv-unit', note: 'Room to come together' },
];
export function EditorialHome() {
  return <>
    <section id="explore-interiors" className={styles.section} aria-labelledby="explore-title">
      <div className={styles.headingRow}><div><span className={styles.kicker}>01 / FIND YOUR INSPIRATION</span><h2 id="explore-title">Every space.<br /><em>Its own possibilities.</em></h2></div><p>From the kitchen you gather in to the storage that simplifies your day. Start with the space you want to make your own.</p></div>
      <div className={styles.categoryGrid}>{categories.map((category, index) => <Link key={category.slug} href={`/categories/${category.slug}`} className={styles.categoryCard}><div data-motion-image={index % 2 === 0 ? "left" : "right"} className={styles.categoryImage}><Image src={`/images/approved/${category.image}.png`} alt={`${category.name} — editorial inspiration`} fill sizes="(max-width: 767px) 90vw, 30vw" /></div><span className={styles.categoryMeta}>0{index + 1} / {category.note}</span><h3>{category.name}<ArrowUpRight size={21} /></h3></Link>)}</div>
      <div className={styles.categoryMore}><span>ALSO EXPLORE</span>{[['Modular cupboards','wardrobes'],['Pooja units','pooja-units'],['Living media walls','tv-units'],['Custom furniture','custom-furniture'],['Bedrooms & suites','bedroom'],['Commercial interiors','commercial']].map(([name,slug]) => <Link key={name} href={`/categories/${slug}`}>{name}<ArrowUpRight size={14} /></Link>)}</div>
      <p className={styles.credit}>AI Concept Visualization — design inspiration, not completed platform projects.</p>
    </section>
    <EditorialProjects />
    <section className={styles.professionals} aria-labelledby="professionals-title"><div data-motion-image="left" className={styles.professionalPhoto}><Image src="/images/generated/hall-cabinetry-v2.png" alt="Detailed walnut and bronze glass cabinetry with burgundy cupboards — AI Concept Visualization" fill sizes="(max-width: 1023px) 100vw, 50vw" /><span className={styles.aiBadge}>AI Concept Visualization</span></div><div className={styles.professionalCopy}><span className={styles.kicker}>03 / MEET THE MAKERS</span><h2 id="professionals-title">Find the professional<br /><em>behind the work.</em></h2><p>The best spaces begin with the right conversation. Discover designers, architects, and cabinetry craftspeople whose work speaks to you.</p><ul><li>Interior designers & design studios</li><li>Architects & architecture firms</li><li>Custom cabinetry & modular wardrobe makers</li><li>Turnkey interior contractors</li></ul><Link className={styles.textLink} href="/professionals">Find your professional <ArrowUpRight size={18} /></Link></div></section>
    <section id="ai-visualizer" className={`${styles.section} ${styles.aiSection}`} aria-labelledby="ai-title"><div><span className={styles.kicker}>04 / EXPLORE WHAT COULD BE</span><h2 id="ai-title">Visualize.<br /><em>Then make it yours.</em></h2><p>Explore materials, finishes and layout ideas with your professional before making decisions on site.</p><Link className={styles.textLink} href="/workspace/ai">Explore the AI workspace <ArrowUpRight size={18} /></Link><p className={styles.disclaimer}>AI Concept Visualization — concepts are creative interpretations, not completed projects or construction specifications. Colors, materials and geometry may vary.</p></div><div className={styles.aiProcess} aria-label="AI visualization workflow"><span>YOUR SPACE → YOUR POSSIBILITIES</span><ol><li><span>01</span><div><h3>Start with your room.</h3><p>Use a photograph of your space.</p></div></li><li><span>02</span><div><h3>Explore a direction.</h3><p>Guide materials and finishes with your references.</p></div></li><li><span>03</span><div><h3>Discuss the concept.</h3><p>Review ideas together. Verify details before building.</p></div></li></ol></div></section>
    <section className={styles.trust} aria-labelledby="trust-title"><span className={styles.kicker}>CONFIDENCE, WITH CONTEXT</span><h2 id="trust-title">Make a more informed choice.</h2><div>{[{icon:Check,title:'Discover the work',copy:'Explore published project stories and the professionals credited for them.'},{icon:MessageSquare,title:'Read client experiences',copy:'Invited client reviews are separate from studio-authored testimonials.'},{icon:ShieldCheck,title:'Understand verification',copy:'Verified Business means evidence has been reviewed. It is not a quality guarantee.'}].map(({icon:Icon,title,copy}) => <article key={title}><Icon size={22} strokeWidth={1.3}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section id="portfolio-builder" className={styles.finalCta}><span className={styles.kicker}>YOUR NEXT CHAPTER STARTS HERE</span><h2>Find the interior<br /><em>that feels like you.</em></h2><div><Link href="/projects" className={styles.primaryLink}>Explore projects <ArrowUpRight size={18}/></Link><Link href="/professionals" className={styles.textLink}>Find professionals <ArrowUpRight size={18}/></Link></div><p>Design for a living? <Link href="/onboarding/professional">Build your portfolio.</Link></p></section>
  </>;
}


