import {
  Project,
  Professional,
  CategoryInfo,
  LocationInfo,
  StyleKey,
  BudgetRangeKey,
  PropertyTypeKey,
  ProfessionalTypeKey,
} from './types';
import { rawSiteSvg, aiConceptSvg, executedSpaceSvg } from '@/app/design-system/mockData';

// Helper to create clean vector SVG data URIs
function createProjectSvg(title: string, sub: string, bg: string, accent: string): string {
  return `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600" width="800" height="600">
    <rect width="800" height="600" fill="%23${bg}"/>
    <rect x="50" y="50" width="700" height="500" fill="%231a1816" rx="16" stroke="%23332e29" stroke-width="2"/>
    <circle cx="400" cy="240" r="130" fill="%23${accent}" opacity="0.3"/>
    <rect x="140" y="340" width="520" height="120" fill="%2324201d" rx="8" stroke="%23${accent}" stroke-width="1.5"/>
    <line x1="140" y1="344" x2="660" y2="344" stroke="%23${accent}" stroke-width="3"/>
    <text x="400" y="270" fill="%23FAF8F5" font-family="Georgia, serif" font-size="28" font-weight="bold" text-anchor="middle">${encodeURIComponent(title)}</text>
    <text x="400" y="410" fill="%23B88A5A" font-family="sans-serif" font-size="16" font-weight="600" text-anchor="middle">${encodeURIComponent(sub)}</text>
  </svg>`;
}

// -------------------------------------------------------------
// Taxonomies
// -------------------------------------------------------------

export const CATEGORIES: { slug: string; name: string }[] = [
  { slug: 'tv-units', name: 'TV Units' },
  { slug: 'modular-kitchens', name: 'Modular Kitchens' },
  { slug: 'bedroom', name: 'Bedroom' },
  { slug: 'wardrobes', name: 'Wardrobes' },
  { slug: 'living-room', name: 'Living Room' },
  { slug: 'pooja-units', name: 'Pooja Units' },
  { slug: 'crockery-units', name: 'Crockery Units' },
  { slug: 'study-units', name: 'Study Units' },
  { slug: 'false-ceiling', name: 'False Ceiling' },
  { slug: 'wall-panels', name: 'Wall Panels' },
  { slug: 'shoe-racks', name: 'Shoe Racks' },
  { slug: 'office', name: 'Office' },
  { slug: 'commercial', name: 'Commercial' },
  { slug: 'custom-furniture', name: 'Custom Furniture' },
  { slug: 'complete-home-interior', name: 'Complete Home Interior' },
];

export const LOCATIONS: { slug: string; name: string; state: string }[] = [
  { slug: 'guntur', name: 'Guntur', state: 'Andhra Pradesh' },
  { slug: 'amaravati', name: 'Amaravati', state: 'Andhra Pradesh' },
  { slug: 'vijayawada', name: 'Vijayawada', state: 'Andhra Pradesh' },
  { slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana' },
  { slug: 'visakhapatnam', name: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { slug: 'bangalore', name: 'Bangalore', state: 'Karnataka' },
];

export const STYLES: { slug: StyleKey; name: string }[] = [
  { slug: 'modern', name: 'Modern' },
  { slug: 'contemporary', name: 'Contemporary' },
  { slug: 'minimal', name: 'Minimal' },
  { slug: 'luxury', name: 'Luxury' },
  { slug: 'traditional', name: 'Traditional' },
  { slug: 'warm-natural', name: 'Warm / Natural' },
  { slug: 'industrial', name: 'Industrial' },
  { slug: 'scandinavian', name: 'Scandinavian' },
];

export const BUDGET_RANGES: { slug: BudgetRangeKey; label: string }[] = [
  { slug: 'under-50k', label: 'Under ₹50K' },
  { slug: '50k-1l', label: '₹50K – ₹1L' },
  { slug: '1l-3l', label: '₹1L – ₹3L' },
  { slug: '3l-5l', label: '₹3L – ₹5L' },
  { slug: '5l-plus', label: '₹5L+' },
];

export const PROPERTY_TYPES: { slug: PropertyTypeKey; name: string }[] = [
  { slug: 'apartment', name: 'Apartment' },
  { slug: 'villa', name: 'Villa' },
  { slug: 'independent-house', name: 'Independent House' },
  { slug: 'office', name: 'Office' },
  { slug: 'commercial', name: 'Retail / Commercial' },
];

export const PROFESSIONAL_TYPES: { slug: ProfessionalTypeKey; name: string }[] = [
  { slug: 'interior-designer', name: 'Interior Designer' },
  { slug: 'interior-studio', name: 'Interior Studio' },
  { slug: 'architect', name: 'Architect' },
  { slug: 'architecture-studio', name: 'Architecture Studio' },
  { slug: 'custom-furniture', name: 'Custom Furniture Studio' },
  { slug: 'woodwork-cabinetry', name: 'Woodwork / Cabinetry' },
  { slug: 'turnkey-contractor', name: 'Turnkey Contractor' },
];

export const SORT_OPTIONS = [
  { value: 'recommended', label: 'Recommended' },
  { value: 'newest', label: 'Newest First' },
  { value: 'most_viewed', label: 'Most Viewed' },
];

// -------------------------------------------------------------
// Category Landing Data
// -------------------------------------------------------------

export const DEMO_CATEGORIES: CategoryInfo[] = [
  {
    slug: 'tv-units',
    name: 'TV Units',
    description: 'Bespoke entertainment walls, fluted acoustic paneling, and floating media credenzas.',
    heroDescription: 'From floating marble consoles to full-height acoustic fluted paneling with concealed wiring channels, explore handcrafted TV units built by regional practitioners.',
    popularStyles: ['Modern', 'Contemporary', 'Minimal', 'Luxury'],
  },
  {
    slug: 'modular-kitchens',
    name: 'Modular Kitchens',
    description: 'Ergonomic kitchen layouts, quartz surfaces, pantry pull-outs, and anti-fingerprint finishes.',
    heroDescription: 'Discover tailored culinary spaces engineered with boiling-water-resistant plywood, Blum tandem runners, and heat-resistant quartz worktops.',
    popularStyles: ['Minimal', 'Modern', 'Contemporary', 'Warm / Natural'],
  },
  {
    slug: 'bedroom',
    name: 'Bedroom Suites',
    description: 'Master bedroom suites, acoustic headboards, integrated wardrobes, and ambient cove illumination.',
    heroDescription: 'Calm, restorative bedroom designs featuring custom padded headboard walls, bedside niches, and seamless dressers.',
    popularStyles: ['Contemporary', 'Minimal', 'Scandinavian', 'Luxury'],
  },
  {
    slug: 'wardrobes',
    name: 'Wardrobes',
    description: 'Floor-to-ceiling floor wardrobes, tinted glass shutters, and tailored internal organizers.',
    heroDescription: 'Walk-in closets and built-in wardrobe systems crafted with sliding or hinged shutters, satin champagne profiles, and illuminated garment rails.',
    popularStyles: ['Modern', 'Luxury', 'Minimal'],
  },
  {
    slug: 'pooja-units',
    name: 'Pooja Units',
    description: 'Sacred spaces with brass accents, carved backdrops, teakwood lattices, and tranquil ambient glow.',
    heroDescription: 'Sacred architectural shrines crafted with solid teak, backlit onyx, brass bells, and laser-cut mandir screens honoring regional traditions.',
    popularStyles: ['Traditional', 'Contemporary', 'Warm / Natural'],
  },
  {
    slug: 'living-room',
    name: 'Living Room',
    description: 'Open-concept living rooms, formal foyers, and bespoke partition walls.',
    heroDescription: 'Curated living spaces blending bespoke seating, architectural wall textures, and multi-tier lighting design.',
    popularStyles: ['Modern', 'Luxury', 'Contemporary'],
  },
  {
    slug: 'crockery-units',
    name: 'Crockery Units',
    description: 'Dining room display cabinets, fluted glass shutters, and integrated wine niches.',
    heroDescription: 'Functional dining storage with ambient internal strip lighting, smoked glass doors, and quartz service ledges.',
    popularStyles: ['Modern', 'Contemporary'],
  },
  {
    slug: 'complete-home-interior',
    name: 'Complete Home Interior',
    description: 'Turnkey residential interiors spanning foyer, living, dining, kitchen, and all bedrooms.',
    heroDescription: 'Comprehensive turnkey transformations delivered with single-window accountability across false ceilings, joinery, and styling.',
    popularStyles: ['Modern', 'Contemporary', 'Luxury', 'Warm / Natural'],
  },
];

// -------------------------------------------------------------
// Location Landing Data
// -------------------------------------------------------------

export const DEMO_LOCATIONS: LocationInfo[] = [
  {
    slug: 'guntur',
    name: 'Guntur',
    state: 'Andhra Pradesh',
    description: 'Explore bespoke interior projects and residential studios across Lakshmipuram, Brodipet, and Pattabhipuram.',
    popularCategories: ['TV Units', 'Modular Kitchens', 'Pooja Units', 'Wardrobes'],
  },
  {
    slug: 'amaravati',
    name: 'Amaravati',
    state: 'Andhra Pradesh',
    description: 'Contemporary architecture, villas, and modern residential developments in the Andhra Pradesh capital region.',
    popularCategories: ['Modular Kitchens', 'Complete Home Interior', 'Living Room', 'TV Units'],
  },
  {
    slug: 'vijayawada',
    name: 'Vijayawada',
    state: 'Andhra Pradesh',
    description: 'Luxury apartments and turnkey interior projects along Bandar Road, Benz Circle, and Kanuru.',
    popularCategories: ['Pooja Units', 'TV Units', 'Modular Kitchens', 'Bedroom'],
  },
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    description: 'High-end architectural residences, penthouses, and minimalist apartments across Jubilee Hills, Gachibowli, and Banjara Hills.',
    popularCategories: ['Complete Home Interior', 'TV Units', 'Wardrobes', 'Modular Kitchens'],
  },
  {
    slug: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    description: 'Coastal residences, sea-facing balconies, and contemporary modular joinery in Lawson’s Bay and MVP Colony.',
    popularCategories: ['Living Room', 'Modular Kitchens', 'TV Units'],
  },
  {
    slug: 'bangalore',
    name: 'Bangalore',
    state: 'Karnataka',
    description: 'Urban apartments, Scandinavian penthouses, and Japandi villas across Indiranagar, Whitefield, and Koramangala.',
    popularCategories: ['Modular Kitchens', 'Living Room', 'Complete Home Interior'],
  },
];

// -------------------------------------------------------------
// Professionals (Studios & Practitioners)
// -------------------------------------------------------------

export const DEMO_PROFESSIONALS: Professional[] = [
  {
    id: 'prof-1',
    slug: 'studio-elegance',
    name: 'Vikram Sharma',
    studioName: 'Studio Elégance',
    professionalType: 'interior-studio',
    professionalTypeLabel: 'Interior Studio',
    location: 'guntur',
    locationName: 'Guntur, Andhra Pradesh',
    bio: 'Studio Elégance specializes in bespoke contemporary residential interiors, architectural woodwork, and integrated ambient lighting systems across Guntur and the Amaravati capital region.',
    services: ['Turnkey Interior Design', 'Bespoke TV Consoles', 'Modular Kitchens', 'Architectural Lighting'],
    specialties: ['Fluted Paneling', 'Italian Marble Bookmatching', 'Warm Ambient Lighting'],
    startingBudgetLabel: '₹1.5 Lakhs',
    serviceAreas: ['Guntur', 'Amaravati', 'Vijayawada'],
    featured: true,
    avatarChar: 'E',
    avatarColor: '#B88A5A',
  },
  {
    id: 'prof-2',
    slug: 'atelier-earth',
    name: 'Priya Rao',
    studioName: 'Atelier Earth',
    professionalType: 'architecture-studio',
    professionalTypeLabel: 'Architecture Studio',
    location: 'amaravati',
    locationName: 'Amaravati Capital Region',
    bio: 'Atelier Earth combines natural materials, biophilic layouts, and minimalist Scandinavian aesthetics to deliver tranquil residential spaces and villas.',
    services: ['Architectural Planning', 'Japandi Interior Styling', 'Sustainable Joinery', 'Landscape Integration'],
    specialties: ['Microcement Finishes', 'Natural Smoked Oak', 'Concealed Storage'],
    startingBudgetLabel: '₹3 Lakhs',
    serviceAreas: ['Amaravati', 'Guntur', 'Vijayawada', 'Hyderabad'],
    featured: true,
    avatarChar: 'A',
    avatarColor: '#2E5D4B',
  },
  {
    id: 'prof-3',
    slug: 'varma-design-studio',
    name: 'Arun Varma',
    studioName: 'Varma Design Studio',
    professionalType: 'interior-designer',
    professionalTypeLabel: 'Interior Designer',
    location: 'hyderabad',
    locationName: 'Hyderabad, Telangana',
    bio: 'With 12+ years of experience across Banjara Hills and Jubilee Hills, Arun Varma crafts luxury penthouses, walk-in closets, and master suites with refined metallic accents.',
    services: ['Luxury Residential Interiors', 'Walk-in Wardrobes', 'Home Theatres', 'Artisan Furniture Curation'],
    specialties: ['Tinted Glass Wardrobes', 'Champagne Brass Accents', 'Plush Headboard Walls'],
    startingBudgetLabel: '₹5 Lakhs',
    serviceAreas: ['Hyderabad', 'Secunderabad', 'Vijayawada'],
    featured: true,
    avatarChar: 'V',
    avatarColor: '#C76F4A',
  },
  {
    id: 'prof-4',
    slug: 'amaravati-woodcraft',
    name: 'K. Venkatesh',
    studioName: 'Amaravati Woodcraft',
    professionalType: 'woodwork-cabinetry',
    professionalTypeLabel: 'Woodwork / Cabinetry',
    location: 'amaravati',
    locationName: 'Amaravati, Andhra Pradesh',
    bio: 'Factory-direct modular cabinetry, precision carcass assembly, and bespoke furniture joinery utilizing calibrated IS:710 marine plywood.',
    services: ['Custom Carcasses', 'Modular Kitchen Cabinets', 'Pooja Mandir Units', 'Shoe Consoles'],
    specialties: ['Marine Plywood Joinery', 'Soft-Close Hardware', 'PU Gloss Finishes'],
    startingBudgetLabel: '₹75,000',
    serviceAreas: ['Amaravati', 'Guntur', 'Vijayawada'],
    featured: false,
    avatarChar: 'W',
    avatarColor: '#3E6D8C',
  },
  {
    id: 'prof-5',
    slug: 'sri-krishna-turnkey',
    name: 'R. Krishna Murthy',
    studioName: 'Sri Krishna Turnkey Solutions',
    professionalType: 'turnkey-contractor',
    professionalTypeLabel: 'Turnkey Contractor',
    location: 'vijayawada',
    locationName: 'Vijayawada, Andhra Pradesh',
    bio: 'Complete end-to-end site execution handling civil demolition, electrical layout, false ceiling framing, painting, modular installation, and final handover.',
    services: ['Complete Flat Interiors', 'False Ceilings & POP', 'Electrical & Plumbing', 'Tiling & Flooring'],
    specialties: ['Rapid 45-Day Handover', 'Quality Control Inspections', 'Single-Window Execution'],
    startingBudgetLabel: '₹2 Lakhs',
    serviceAreas: ['Vijayawada', 'Guntur', 'Tenali'],
    featured: false,
    avatarChar: 'K',
    avatarColor: '#1F1F1F',
  },
  {
    id: 'prof-6',
    slug: 'deccan-architectural-labs',
    name: 'Suhasini Reddy',
    studioName: 'Deccan Architectural Labs',
    professionalType: 'architect',
    professionalTypeLabel: 'Architect',
    location: 'hyderabad',
    locationName: 'Hyderabad, Telangana',
    bio: 'Spatial architecture studio focused on light wells, double-height volumes, and climate-responsive courtyard homes.',
    services: ['Villa Architecture', 'Structural Renovation', 'Interior Architecture', 'Courtyard Landscapes'],
    specialties: ['Exposed Brickwork', 'Corten Steel Details', 'Double-Height Living Rooms'],
    startingBudgetLabel: '₹8 Lakhs',
    serviceAreas: ['Hyderabad', 'Amaravati', 'Bangalore'],
    featured: true,
    avatarChar: 'D',
    avatarColor: '#B88A5A',
  },
];

// -------------------------------------------------------------
// Demo Projects (16 High-Quality Projects)
// -------------------------------------------------------------

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    slug: 'modern-fluted-tv-unit-guntur',
    title: 'Modern Fluted TV Unit & Statuario Console',
    category: 'tv-units',
    categoryName: 'TV Units',
    location: 'guntur',
    locationName: 'Guntur, Andhra Pradesh',
    style: 'modern',
    styleName: 'Modern',
    budgetRange: '1l-3l',
    budgetLabel: '₹1.8 Lakhs',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'interior-studio',
    professionalTypeName: 'Interior Studio',
    professionalSlug: 'studio-elegance',
    professionalName: 'Vikram Sharma',
    studioName: 'Studio Elégance',
    description: 'A 75-inch entertainment wall featuring bookmatched Italian Statuario composite marble framed by 12mm CNC-fluted American walnut panelling. Finished with warm 3000K indirect cove lighting and a floating credenza with brushed brass edge pulls.',
    scope: 'Living room feature wall, structural framing, electrical relocation, veneer polish, and cove LED installation.',
    coverImage: createProjectSvg('Modern Fluted TV Unit', 'Guntur, AP • Studio Elégance', '1f1d1b', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('TV Unit Full Elevation', 'Bookmatched Marble & Smoked Walnut', '1f1d1b', 'B88A5A'),
        alt: 'Full frontal view of modern fluted TV unit with ambient cove lighting',
        caption: 'Frontal elevation showing symmetrical fluted walnut panels',
        orientation: 'landscape',
      },
      {
        url: createProjectSvg('Joinery & Hardware Detail', 'Brushed Brass Linear Pulls', '24201d', 'B88A5A'),
        alt: 'Detail view of brushed brass hardware and 45-degree mitred floating drawer',
        caption: 'Precision mitred drawer corners and concealed Blum runners',
        orientation: 'portrait',
      },
      {
        url: createProjectSvg('Night Lighting Ambience', '3000K Indirect Warm Glow', '141312', 'B88A5A'),
        alt: 'Low-light photograph demonstrating indirect cove illumination',
        caption: 'Concealed LED cove profile providing non-glare evening illumination',
        orientation: 'landscape',
      },
    ],
    materials: ['Italian Statuario Composite', 'Smoked American Walnut Veneer', 'Champagne Brass Profiles', 'BWP Marine Ply (IS:710)'],
    completionYear: 2025,
    duration: '18 Days',
    services: ['Woodwork', 'Marble Cladding', 'Electrical & Lighting'],
    featured: true,
    createdAt: '2025-11-10',
    viewCount: '3.8k',
    // Signature 3-stage transformation data available for this project
    beforeImage: rawSiteSvg,
    aiImage: aiConceptSvg,
    realityImage: executedSpaceSvg,
  },
  {
    id: 'proj-2',
    slug: 'japandi-modular-kitchen-amaravati',
    title: 'Minimalist Japandi Modular Kitchen with Island',
    category: 'modular-kitchens',
    categoryName: 'Modular Kitchens',
    location: 'amaravati',
    locationName: 'Amaravati, Andhra Pradesh',
    style: 'minimal',
    styleName: 'Minimal',
    budgetRange: '3l-5l',
    budgetLabel: '₹3.6 Lakhs',
    propertyType: 'villa',
    propertyTypeName: 'Villa',
    professionalType: 'architecture-studio',
    professionalTypeName: 'Architecture Studio',
    professionalSlug: 'atelier-earth',
    professionalName: 'Priya Rao',
    studioName: 'Atelier Earth',
    description: 'An open-concept kitchen blending natural light oak finishes with seamless chalk-white acrylic shutters. Features a 7-foot quartz waterfall breakfast island and dedicated appliance garage.',
    scope: 'Complete kitchen overhaul, plumbing lines, anti-fingerprint cabinetry, and quartz fabrication.',
    coverImage: createProjectSvg('Japandi Kitchen & Island', 'Amaravati • Atelier Earth', '1a211c', '2E5D4B'),
    gallery: [
      {
        url: createProjectSvg('Kitchen Island View', 'Quartz Waterfall Counter', '1a211c', '2E5D4B'),
        alt: 'Minimalist kitchen island with integrated sink and matte black tapware',
        orientation: 'landscape',
      },
      {
        url: createProjectSvg('Tall Pantry Organization', 'Soft-close Tandem Pull-outs', '202a24', '2E5D4B'),
        alt: 'Internal tall larder unit with chrome wire pullouts',
        orientation: 'portrait',
      },
    ],
    materials: ['Calacatta Gold Quartz', 'Natural Light Oak Shutter Finish', 'Anti-Fingerprint Matte White Laminate', 'Blum Legrabox'],
    completionYear: 2025,
    duration: '25 Days',
    services: ['Modular Kitchen', 'Countertop Fabrication', 'Plumbing'],
    featured: true,
    createdAt: '2025-12-04',
    viewCount: '4.2k',
  },
  {
    id: 'proj-3',
    slug: 'fluted-master-bedroom-suite-hyderabad',
    title: 'Fluted Master Suite & Walk-in Wardrobe',
    category: 'bedroom',
    categoryName: 'Bedroom',
    location: 'hyderabad',
    locationName: 'Hyderabad, Telangana',
    style: 'luxury',
    styleName: 'Luxury',
    budgetRange: '5l-plus',
    budgetLabel: '₹5.4 Lakhs',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'interior-designer',
    professionalTypeName: 'Interior Designer',
    professionalSlug: 'varma-design-studio',
    professionalName: 'Arun Varma',
    studioName: 'Varma Design Studio',
    description: 'A luxurious master bedroom suite featuring an upholstered suede fluted headboard running wall-to-wall, smoked grey glass wardrobe shutters with interior sensor lighting, and floating nightstands.',
    scope: 'False ceiling with peripheral magnetic track lighting, wooden flooring, custom headboard, and walk-in wardrobe.',
    coverImage: createProjectSvg('Master Suite & Walk-in', 'Banjara Hills • Varma Design', '241b18', 'C76F4A'),
    gallery: [
      {
        url: createProjectSvg('Bed Elevation', 'Full-height Suede Headboard', '241b18', 'C76F4A'),
        alt: 'Bed with floating side tables and warm pendant lights',
        orientation: 'landscape',
      },
      {
        url: createProjectSvg('Tinted Glass Wardrobe', 'Fluted Bronze Profiles', '1e1513', 'C76F4A'),
        alt: 'Walk-in wardrobe with bronze framed glass doors',
        orientation: 'portrait',
      },
    ],
    materials: ['Textured Taupe Suede', 'Smoked Grey Toughened Glass', 'Herringbone Engineered Oak', 'Slim Bronze Profiles'],
    completionYear: 2025,
    duration: '30 Days',
    services: ['Master Bedroom', 'Wardrobes', 'Magnetic Track Lighting'],
    featured: true,
    createdAt: '2026-01-15',
    viewCount: '5.1k',
  },
  {
    id: 'proj-4',
    slug: 'traditional-teakwood-pooja-unit-vijayawada',
    title: 'Traditional Teakwood Pooja Mandir with Backlit Onyx',
    category: 'pooja-units',
    categoryName: 'Pooja Units',
    location: 'vijayawada',
    locationName: 'Vijayawada, Andhra Pradesh',
    style: 'traditional',
    styleName: 'Traditional',
    budgetRange: '1l-3l',
    budgetLabel: '₹1.9 Lakhs',
    propertyType: 'villa',
    propertyTypeName: 'Villa',
    professionalType: 'woodwork-cabinetry',
    professionalTypeName: 'Woodwork / Cabinetry',
    professionalSlug: 'amaravati-woodcraft',
    professionalName: 'K. Venkatesh',
    studioName: 'Amaravati Woodcraft',
    description: 'A serene mandir room designed according to Vastu Shastra principles. Features solid Burma teak pillars, a CNC-carved Om backdrop illuminated by honey onyx stone, and deep brass diya drawers.',
    scope: 'Solid teakwood carving, natural stone backlighting, and concealed ventilation.',
    coverImage: createProjectSvg('Traditional Pooja Mandir', 'Vijayawada • Amaravati Woodcraft', '211e17', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Mandir Sanctum', 'Carved Pillars & Backlit Onyx', '211e17', 'B88A5A'),
        alt: 'Pooja sanctum with warm glowing onyx backdrop',
        orientation: 'portrait',
      },
    ],
    materials: ['Natural Burma Teak', 'Honey Translucent Onyx', 'Solid Cast Brass Bells', 'PU Semi-Gloss Polish'],
    completionYear: 2025,
    duration: '21 Days',
    services: ['Pooja Unit', 'Stone Backlighting', 'Vastu Joinery'],
    featured: false,
    createdAt: '2025-10-20',
    viewCount: '2.6k',
  },
  {
    id: 'proj-5',
    slug: 'contemporary-living-room-guntur',
    title: 'Warm Contemporary Living Room & Foyer Partition',
    category: 'living-room',
    categoryName: 'Living Room',
    location: 'guntur',
    locationName: 'Guntur, Andhra Pradesh',
    style: 'contemporary',
    styleName: 'Contemporary',
    budgetRange: '3l-5l',
    budgetLabel: '₹3.2 Lakhs',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'interior-studio',
    professionalTypeName: 'Interior Studio',
    professionalSlug: 'studio-elegance',
    professionalName: 'Vikram Sharma',
    studioName: 'Studio Elégance',
    description: 'A bright 4BHK apartment living room featuring open brass-and-fluted-glass room divider screens, microcement wall coatings, and bespoke low-slung sofa joinery.',
    scope: 'Foyer partition, shoe console, false ceiling, texture wall, and bespoke upholstery.',
    coverImage: createProjectSvg('Contemporary Living Room', 'Guntur • Studio Elégance', '1f1d1b', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Living Lounge Overview', 'Foyer Partition & Sofa', '1f1d1b', 'B88A5A'),
        alt: 'Wide view of contemporary living room and foyer screen',
        orientation: 'landscape',
      },
    ],
    materials: ['Fluted Reeded Glass', 'Brass Square Tubes', 'Italian Microcement', 'Neutral Bouclé Fabric'],
    completionYear: 2026,
    duration: '22 Days',
    services: ['Living Room', 'Partition Screens', 'Ceiling Design'],
    featured: false,
    createdAt: '2026-02-01',
    viewCount: '2.1k',
  },
  {
    id: 'proj-6',
    slug: 'walk-in-wardrobe-island-hyderabad',
    title: 'Smoked Glass Floor-to-Ceiling Wardrobes with Accessory Island',
    category: 'wardrobes',
    categoryName: 'Wardrobes',
    location: 'hyderabad',
    locationName: 'Hyderabad, Telangana',
    style: 'luxury',
    styleName: 'Luxury',
    budgetRange: '3l-5l',
    budgetLabel: '₹4.5 Lakhs',
    propertyType: 'villa',
    propertyTypeName: 'Villa',
    professionalType: 'interior-designer',
    professionalTypeName: 'Interior Designer',
    professionalSlug: 'varma-design-studio',
    professionalName: 'Arun Varma',
    studioName: 'Varma Design Studio',
    description: 'A master walk-in wardrobe featuring floor-to-ceiling smoked grey glass hinged doors, warm 2700K integrated shelf LEDs, and a central velvet-lined watch and jewellery island with a glass top.',
    scope: 'Wardrobe cabinetry, drawer organizers, glass work, and automation sensors.',
    coverImage: createProjectSvg('Smoked Glass Wardrobe', 'Jubilee Hills • Varma Design', '241b18', 'C76F4A'),
    gallery: [
      {
        url: createProjectSvg('Jewellery Island Close-up', 'Velvet Divided Compartments', '241b18', 'C76F4A'),
        alt: 'Accessory island drawer with watch winders and velvet compartments',
        orientation: 'landscape',
      },
    ],
    materials: ['Smoked Toughened Glass', 'Matte Charcoal Aluminum Profiles', 'Burgundy Suede Lining'],
    completionYear: 2025,
    duration: '16 Days',
    services: ['Wardrobe Joinery', 'LED Automation', 'Accessory Storage'],
    featured: true,
    createdAt: '2025-11-28',
    viewCount: '3.9k',
  },
  {
    id: 'proj-7',
    slug: 'scandinavian-open-kitchen-bangalore',
    title: 'Nordic Oak & Sage Green Modular Kitchen',
    category: 'modular-kitchens',
    categoryName: 'Modular Kitchens',
    location: 'bangalore',
    locationName: 'Bangalore, Karnataka',
    style: 'scandinavian',
    styleName: 'Scandinavian',
    budgetRange: '1l-3l',
    budgetLabel: '₹2.8 Lakhs',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'architecture-studio',
    professionalTypeName: 'Architecture Studio',
    professionalSlug: 'atelier-earth',
    professionalName: 'Priya Rao',
    studioName: 'Atelier Earth',
    description: 'A bright apartment kitchen pairing soft sage green matte base cabinets with blonde birch plywood wall modules. Subway tile backsplash and brushed nickel gooseneck faucet.',
    scope: 'Demolition of old counters, waterproof ply modules, tiled backsplash, and under-cabinet puck lights.',
    coverImage: createProjectSvg('Nordic Sage Kitchen', 'Indiranagar • Atelier Earth', '1c2420', '2E5D4B'),
    gallery: [
      {
        url: createProjectSvg('Sage Green Cabinetry', 'Blonde Birch Open Shelves', '1c2420', '2E5D4B'),
        alt: 'Scandinavian kitchen cabinets with open spice shelves',
        orientation: 'landscape',
      },
    ],
    materials: ['Sage Green Matte Acrylic', 'Natural Birch Ply', 'Brushed Nickel Fittings', 'White Composite Stone'],
    completionYear: 2026,
    duration: '20 Days',
    services: ['Modular Kitchen', 'Tiling', 'Plumbing'],
    featured: false,
    createdAt: '2026-01-20',
    viewCount: '1.9k',
  },
  {
    id: 'proj-8',
    slug: 'turnkey-3bhk-interior-amaravati',
    title: 'Complete Turnkey 3BHK Residence Handover',
    category: 'complete-home-interior',
    categoryName: 'Complete Home Interior',
    location: 'amaravati',
    locationName: 'Amaravati, Andhra Pradesh',
    style: 'contemporary',
    styleName: 'Contemporary',
    budgetRange: '5l-plus',
    budgetLabel: '₹9.2 Lakhs',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'turnkey-contractor',
    professionalTypeName: 'Turnkey Contractor',
    professionalSlug: 'sri-krishna-turnkey',
    professionalName: 'R. Krishna Murthy',
    studioName: 'Sri Krishna Turnkey Solutions',
    description: 'A 2,100 sq.ft 3BHK flat completed in 42 days. Encompasses false ceiling throughout, TV unit with fluted charcoal panels, modular kitchen with breakfast counter, 3 bedrooms with built-in wardrobes, and a compact pooja corner.',
    scope: 'Civil repairs, false ceiling, painting (Asian Paints Royale), electrical wiring, all modular joinery, and deep clean.',
    coverImage: createProjectSvg('Turnkey 3BHK Residence', 'Amaravati • Sri Krishna Turnkey', '201f1e', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Living to Dining Vista', 'Coordinated False Ceiling & Lighting', '201f1e', 'B88A5A'),
        alt: 'View from living room to dining area showing consistent architectural theme',
        orientation: 'landscape',
      },
      {
        url: createProjectSvg('Bedroom Wardrobe Wall', 'Sliding 3-Door Wardrobe', '232120', 'B88A5A'),
        alt: 'Guest bedroom sliding wardrobe with full-height mirror panel',
        orientation: 'portrait',
      },
    ],
    materials: ['Greenply BWP Club Ply', 'Merino Laminates', 'Saint-Gobain Gyproc Ceilings', 'Hafele Soft-Close Hinges'],
    completionYear: 2025,
    duration: '42 Days',
    services: ['Complete Flat Interior', 'False Ceiling', 'Electrical & Painting'],
    featured: true,
    createdAt: '2025-12-18',
    viewCount: '4.8k',
  },
  {
    id: 'proj-9',
    slug: 'floating-crockery-dining-console-vijayawada',
    title: 'Floating Fluted Crockery Console with Bar Ledge',
    category: 'crockery-units',
    categoryName: 'Crockery Units',
    location: 'vijayawada',
    locationName: 'Vijayawada, Andhra Pradesh',
    style: 'modern',
    styleName: 'Modern',
    budgetRange: '50k-1l',
    budgetLabel: '₹95,000',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'woodwork-cabinetry',
    professionalTypeName: 'Woodwork / Cabinetry',
    professionalSlug: 'amaravati-woodcraft',
    professionalName: 'K. Venkatesh',
    studioName: 'Amaravati Woodcraft',
    description: 'A sleek 8-foot dining room sideboard suspended 12 inches above the floor. Features fluted glass fronted shutter display, integrated bottle rack, and warm under-counter shadow lighting.',
    scope: 'Wall anchor fabrication, tempered fluted glass installation, and LED profiling.',
    coverImage: createProjectSvg('Floating Crockery Unit', 'Vijayawada • Amaravati Woodcraft', '211e17', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Crockery Unit Elevation', 'Fluted Glass & Wine Rack', '211e17', 'B88A5A'),
        alt: 'Front view of dining console with illuminated stemware shelf',
        orientation: 'landscape',
      },
    ],
    materials: ['MDF Fluted Core', 'Toughened Fluted Glass', 'Matte Champagne Gold Trim', 'Warm 3000K LED Strip'],
    completionYear: 2025,
    duration: '10 Days',
    services: ['Crockery Unit', 'Custom Cabinetry'],
    featured: false,
    createdAt: '2025-09-12',
    viewCount: '1.4k',
  },
  {
    id: 'proj-10',
    slug: 'architectural-courtyard-villa-hyderabad',
    title: 'Biophilic Courtyard Villa with Exposed Brick',
    category: 'complete-home-interior',
    categoryName: 'Complete Home Interior',
    location: 'hyderabad',
    locationName: 'Hyderabad, Telangana',
    style: 'warm-natural',
    styleName: 'Warm / Natural',
    budgetRange: '5l-plus',
    budgetLabel: '₹14 Lakhs',
    propertyType: 'villa',
    propertyTypeName: 'Villa',
    professionalType: 'architect',
    professionalTypeName: 'Architect',
    professionalSlug: 'deccan-architectural-labs',
    professionalName: 'Suhasini Reddy',
    studioName: 'Deccan Architectural Labs',
    description: 'A 3,800 sq.ft villa designed around a central open-to-sky courtyard with a frangipani tree. Natural Kota stone flooring, wire-cut exposed brick walls, and custom recycled teak furniture.',
    scope: 'Architecture, internal courtyard engineering, fenestration design, and bespoke furniture build.',
    coverImage: createProjectSvg('Courtyard Villa Interior', 'Hyderabad • Deccan Arch Labs', '241e17', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Courtyard Light Well', 'Frangipani Tree & Kota Stone', '241e17', 'B88A5A'),
        alt: 'Internal court with skylight and lush potted plants',
        orientation: 'portrait',
      },
    ],
    materials: ['Honed Green Kota Stone', 'Wire-cut Terracotta Bricks', 'Reclaimed Teak Wood', 'Brass Joinery'],
    completionYear: 2025,
    duration: '6 Months',
    services: ['Architectural Design', 'Interior Woodwork', 'Courtyard Landscape'],
    featured: true,
    createdAt: '2025-08-30',
    viewCount: '6.2k',
  },
  {
    id: 'proj-11',
    slug: 'compact-study-unit-guntur',
    title: 'Ergonomic Work-from-Home Study Unit & Bookshelf',
    category: 'study-units',
    categoryName: 'Study Units',
    location: 'guntur',
    locationName: 'Guntur, Andhra Pradesh',
    style: 'minimal',
    styleName: 'Minimal',
    budgetRange: 'under-50k',
    budgetLabel: '₹42,000',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'interior-studio',
    professionalTypeName: 'Interior Studio',
    professionalSlug: 'studio-elegance',
    professionalName: 'Vikram Sharma',
    studioName: 'Studio Elégance',
    description: 'A compact 5-foot study desk with concealed cable management, overhead floating book cubes, and a pinboard upholstered in acoustic grey felt.',
    scope: 'Desk fabrication, wall mounting, and cable trough integration.',
    coverImage: createProjectSvg('Compact Study Unit', 'Guntur • Studio Elégance', '1f1d1b', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Desk & Floating Cubes', 'Oak Laminate with Felt Pinboard', '1f1d1b', 'B88A5A'),
        alt: 'Ergonomic study setup with floating shelf modules',
        orientation: 'landscape',
      },
    ],
    materials: ['Smoked Oak Scratch-Resistant Laminate', 'Acoustic Wool Felt', 'Powder-coated Metal Brackets'],
    completionYear: 2026,
    duration: '5 Days',
    services: ['Custom Study Unit', 'Woodwork'],
    featured: false,
    createdAt: '2026-02-14',
    viewCount: '1.1k',
  },
  {
    id: 'proj-12',
    slug: 'minimalist-shoe-console-foyer-vijayawada',
    title: 'Fluted Foyer Shoe Console with Sitting Ledge',
    category: 'shoe-racks',
    categoryName: 'Shoe Racks',
    location: 'vijayawada',
    locationName: 'Vijayawada, Andhra Pradesh',
    style: 'contemporary',
    styleName: 'Contemporary',
    budgetRange: 'under-50k',
    budgetLabel: '₹38,000',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'woodwork-cabinetry',
    professionalTypeName: 'Woodwork / Cabinetry',
    professionalSlug: 'amaravati-woodcraft',
    professionalName: 'K. Venkatesh',
    studioName: 'Amaravati Woodcraft',
    description: 'An entryway shoe credenza holding 24 pairs with louvred ventilation slits, an upholstered bench for putting on shoes, and a brass key tray niche.',
    scope: 'Foyer measurement, cabinet build with ventilation louvres, and cushion upholstery.',
    coverImage: createProjectSvg('Foyer Shoe Console', 'Vijayawada • Amaravati Woodcraft', '211e17', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Shoe Console Elevation', 'Ventilated Louvres & Seating', '211e17', 'B88A5A'),
        alt: 'Entryway shoe unit with comfortable cushioned seat',
        orientation: 'landscape',
      },
    ],
    materials: ['High-Density Fibreboard (HDF)', 'Breathable Louvred Shutters', 'Leatherette Cushion', 'Brass Hooks'],
    completionYear: 2025,
    duration: '7 Days',
    services: ['Entryway Unit', 'Custom Cabinetry'],
    featured: false,
    createdAt: '2025-11-05',
    viewCount: '980',
  },
  {
    id: 'proj-13',
    slug: 'acoustic-fluted-wall-panels-hyderabad',
    title: 'Acoustic Fluted Wall Paneling & Pivot Door',
    category: 'wall-panels',
    categoryName: 'Wall Panels',
    location: 'hyderabad',
    locationName: 'Hyderabad, Telangana',
    style: 'modern',
    styleName: 'Modern',
    budgetRange: '1l-3l',
    budgetLabel: '₹2.1 Lakhs',
    propertyType: 'villa',
    propertyTypeName: 'Villa',
    professionalType: 'interior-designer',
    professionalTypeName: 'Interior Designer',
    professionalSlug: 'varma-design-studio',
    professionalName: 'Arun Varma',
    studioName: 'Varma Design Studio',
    description: 'A 20-foot seamless acoustic wall paneling system that completely conceals a flush pivot door leading into the private powder room. Crafted with sound-absorbing backing and natural walnut veneer slats.',
    scope: 'Heavy-duty pivot hinge installation, acoustic substrate, and CNC-cut veneer paneling.',
    coverImage: createProjectSvg('Acoustic Wall Paneling', 'Jubilee Hills • Varma Design', '241b18', 'C76F4A'),
    gallery: [
      {
        url: createProjectSvg('Concealed Pivot Door', 'Seamless Flush Closure', '241b18', 'C76F4A'),
        alt: 'Hidden door in seamless wooden wall paneling',
        orientation: 'portrait',
      },
    ],
    materials: ['Natural American Walnut Veneer', 'High-density Rockwool Acoustic Core', 'FritsJurgens Pivot System'],
    completionYear: 2025,
    duration: '14 Days',
    services: ['Wall Cladding', 'Concealed Doors', 'Acoustics'],
    featured: false,
    createdAt: '2025-10-12',
    viewCount: '2.4k',
  },
  {
    id: 'proj-14',
    slug: 'cove-lit-gypsum-ceiling-visakhapatnam',
    title: 'Minimalist Linear Cove False Ceiling with Magnetic Tracks',
    category: 'false-ceiling',
    categoryName: 'False Ceiling',
    location: 'visakhapatnam',
    locationName: 'Visakhapatnam, Andhra Pradesh',
    style: 'minimal',
    styleName: 'Minimal',
    budgetRange: '50k-1l',
    budgetLabel: '₹88,000',
    propertyType: 'apartment',
    propertyTypeName: 'Apartment',
    professionalType: 'turnkey-contractor',
    professionalTypeName: 'Turnkey Contractor',
    professionalSlug: 'sri-krishna-turnkey',
    professionalName: 'R. Krishna Murthy',
    studioName: 'Sri Krishna Turnkey Solutions',
    description: 'A clean 12mm gypsum ceiling with a zero-drop perimeter reveal, recessed magnetic track channels, and high-CRI warm white cove LED illumination.',
    scope: 'GI metal framing, moisture-resistant gypsum boards, plaster jointing, and track lighting integration.',
    coverImage: createProjectSvg('Linear Cove Ceiling', 'Visakhapatnam • Sri Krishna', '201f1e', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Ceiling Track Detail', 'Recessed Magnetic Lighting Channel', '201f1e', 'B88A5A'),
        alt: 'Ceiling corner showing crisp shadow gap reveal and light track',
        orientation: 'landscape',
      },
    ],
    materials: ['Saint-Gobain Gyproc Boards', 'Galvanized Steel Sub-Grid', '3000K Linear LED Profiles'],
    completionYear: 2025,
    duration: '8 Days',
    services: ['False Ceiling', 'Lighting Profiling'],
    featured: false,
    createdAt: '2025-11-19',
    viewCount: '1.3k',
  },
  {
    id: 'proj-15',
    slug: 'custom-live-edge-dining-table-amaravati',
    title: 'Custom Live-Edge Suar Wood 8-Seater Dining Table',
    category: 'custom-furniture',
    categoryName: 'Custom Furniture',
    location: 'amaravati',
    locationName: 'Amaravati, Andhra Pradesh',
    style: 'warm-natural',
    styleName: 'Warm / Natural',
    budgetRange: '1l-3l',
    budgetLabel: '₹1.4 Lakhs',
    propertyType: 'villa',
    propertyTypeName: 'Villa',
    professionalType: 'architecture-studio',
    professionalTypeName: 'Architecture Studio',
    professionalSlug: 'atelier-earth',
    professionalName: 'Priya Rao',
    studioName: 'Atelier Earth',
    description: 'An 8.5-foot single slab live-edge dining table preserved with natural food-safe hardwax oil and supported on architectural matte black spider legs.',
    scope: 'Timber kiln drying, butterfly key joinery, levelling, and metal base fabrication.',
    coverImage: createProjectSvg('Live Edge Dining Table', 'Amaravati • Atelier Earth', '1a211c', '2E5D4B'),
    gallery: [
      {
        url: createProjectSvg('Wood Grain & Edge Detail', 'Butterfly Inlays & Natural Curves', '1a211c', '2E5D4B'),
        alt: 'Macro view of natural timber grain and brass butterfly stabilization key',
        orientation: 'landscape',
      },
    ],
    materials: ['Solid Single-Slab Suar Timber', 'Osmo Polyx Hardwax Oil', 'Heavy-gauge Mild Steel Spider Base'],
    completionYear: 2025,
    duration: '15 Days',
    services: ['Custom Furniture', 'Timber Finishing'],
    featured: false,
    createdAt: '2025-12-22',
    viewCount: '2.2k',
  },
  {
    id: 'proj-16',
    slug: 'boutique-studio-office-interior-hyderabad',
    title: 'Boutique Creative Agency Studio Interior',
    category: 'office',
    categoryName: 'Office',
    location: 'hyderabad',
    locationName: 'Hyderabad, Telangana',
    style: 'industrial',
    styleName: 'Industrial',
    budgetRange: '5l-plus',
    budgetLabel: '₹7.8 Lakhs',
    propertyType: 'office',
    propertyTypeName: 'Office',
    professionalType: 'architect',
    professionalTypeName: 'Architect',
    professionalSlug: 'deccan-architectural-labs',
    professionalName: 'Suhasini Reddy',
    studioName: 'Deccan Architectural Labs',
    description: 'A 1,600 sq.ft industrial workspace featuring exposed air-conditioning ducts, polished concrete floors, steel-and-glass conference pods, and hot-rolled steel work tables.',
    scope: 'Commercial interior fitout, glass cubicles, HVAC distribution, and acoustic ceiling panels.',
    coverImage: createProjectSvg('Boutique Studio Office', 'Gachibowli • Deccan Arch Labs', '241e17', 'B88A5A'),
    gallery: [
      {
        url: createProjectSvg('Conference Glass Pod', 'Black Aluminum Slim Frames', '241e17', 'B88A5A'),
        alt: 'Acoustic glass meeting room overlooking open workstations',
        orientation: 'landscape',
      },
    ],
    materials: ['Polished Concrete', 'Hot-Rolled Mild Steel', '12mm Acoustic Glass', 'Exposed Spiral Galvanized Ducts'],
    completionYear: 2026,
    duration: '35 Days',
    services: ['Commercial Architecture', 'Office Fitout', 'HVAC & Partitioning'],
    featured: false,
    createdAt: '2026-01-28',
    viewCount: '1.7k',
  },
];
