import React from 'react';import{afterEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render,screen}from'@testing-library/react';import{renderToString}from'react-dom/server';import{ArchitecturalTemplate}from'../portfolio/templates/architectural/ArchitecturalTemplate';import{basicFixture}from'./BasicTemplate.fixture';import{safeUrl}from'../portfolio/templates/architectural/architectural';import{TEMPLATE_REGISTRY}from'@/lib/portfolio/template-registry';import type{PreviewSectionDto}from'@/lib/portfolio/types';
afterEach(()=>{cleanup();vi.restoreAllMocks()});const s=(type:PreviewSectionDto['sectionType'],content:Record<string,unknown>):PreviewSectionDto=>({sectionId:type,sectionType:type,displayOrder:1,schemaVersion:1,content});
describe('ARCHITECTURAL production presentation',()=>{
it('renders semantic monograph structure without API access',()=>{const f=vi.spyOn(globalThis,'fetch');render(<ArchitecturalTemplate {...basicFixture({templateKey:'ARCHITECTURAL'})}/>);expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);expect(screen.getByRole('banner')).toBeTruthy();expect(screen.getByRole('main')).toBeTruthy();expect(screen.getByRole('contentinfo')).toBeTruthy();expect(f).not.toHaveBeenCalled()});
it('preserves section order and hides empty project/media sections',()=>{const list=[s('SERVICES',{}),s('HERO',{}),s('FEATURED_PROJECTS',{projectIds:['future']}),s('ABOUT',{narrativeOverride:'Supplied'})];const before=JSON.stringify(list);const{container}=render(<ArchitecturalTemplate {...basicFixture({templateKey:'ARCHITECTURAL',visibleSections:list,canonicalServices:[]})}/>);expect([...container.querySelectorAll('section')].map(x=>x.id)).toEqual(['hero','about']);expect(JSON.stringify(list)).toBe(before)});
it('renders structured services, process and editorial records',()=>{render(<ArchitecturalTemplate {...basicFixture({templateKey:'ARCHITECTURAL',visibleSections:[s('SERVICES',{}),s('DESIGN_PROCESS',{steps:[{step:'01',title:'Brief',desc:'Supplied detail'}]}),s('AWARDS',{items:[{year:'2024',title:'Supplied award',category:'Residential'}]})]})}/>);expect(screen.getByText('Interior design')).toBeTruthy();expect(screen.getByText('Brief')).toBeTruthy();expect(screen.getByText('Supplied award')).toBeTruthy()});
it('supports accessible mobile navigation and contact privacy',()=>{render(<ArchitecturalTemplate {...basicFixture({templateKey:'ARCHITECTURAL',visibleSections:[s('CONTACT',{contactIntro:'Contact'})],publicContacts:[{kind:'EMAIL',contactValue:'public@example.com'},{kind:'PHONE',contactValue:'private'}]})}/>);const menu=screen.getByRole('button',{name:'Index'});fireEvent.click(menu);expect(menu.getAttribute('aria-expanded')).toBe('true');fireEvent.keyDown(menu,{key:'Escape'});expect(menu.getAttribute('aria-expanded')).toBe('false');expect(screen.getByRole('link',{name:/public@example.com/})).toBeTruthy();expect(screen.queryByText('private')).toBeNull()});
it('handles empty data without fabricated content',()=>{const{container}=render(<ArchitecturalTemplate {...basicFixture({templateKey:'ARCHITECTURAL',visibleSections:[s('FEATURED_PROJECTS',{}),s('PROJECT_GRID',{}),s('TEAM',{members:[]}),s('TESTIMONIALS',{items:[]}),s('CONTACT',{}),s('VIDEO',{})],publicContacts:[],canonicalServices:[],canonicalServiceAreas:[]})}/>);expect(container.querySelectorAll('section')).toHaveLength(1);expect(container.textContent).not.toMatch(/undefined|TODO|Verified/)})
it('preserves long content in SSR and safe URL boundaries',()=>{const long='Long architectural practice '.repeat(14).trim();expect(renderToString(<ArchitecturalTemplate {...basicFixture({templateKey:'ARCHITECTURAL',studioName:long,headline:long})}/>)).toContain(long);for(const u of['javascript:alert(1)','data:text/html,x','file:///x','https://user:pass@example.com','#missing'])expect(safeUrl(u)).toBeUndefined()});
it('keeps canonical template lifecycle and no unsafe dependencies',()=>{expect(TEMPLATE_REGISTRY.ARCHITECTURAL.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.ARCHITECTURAL.isSelectable).toBe(true);expect(TEMPLATE_REGISTRY.WARM_NATURAL.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.DARK_CINEMATIC.status).toBe('AVAILABLE');const fs=require('node:fs');const path=require('node:path');for(const file of fs.readdirSync(path.resolve('src/components/portfolio/templates/architectural')).filter((x:string)=>/\.[tj]sx?$/.test(x))){const source=fs.readFileSync(path.resolve('src/components/portfolio/templates/architectural',file),'utf8');expect(source).not.toMatch(/apiFetch|AuthContext|fetch\(|localStorage|sessionStorage|dangerouslySetInnerHTML|\/lib\/auth/)}});
});


