import React from 'react';import{afterEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render,screen}from'@testing-library/react';import{renderToString}from'react-dom/server';import{LuxuryTemplate}from'../portfolio/templates/luxury/LuxuryTemplate';import{basicFixture}from'./BasicTemplate.fixture';import{safeUrl}from'../portfolio/templates/luxury/luxury';import type{PreviewSectionDto}from'@/lib/portfolio/types';import{TEMPLATE_REGISTRY}from'@/lib/portfolio/template-registry';
afterEach(()=>{cleanup();vi.restoreAllMocks()});const s=(type:PreviewSectionDto['sectionType'],content:Record<string,unknown>):PreviewSectionDto=>({sectionId:type,sectionType:type,displayOrder:1,schemaVersion:1,content});
describe('LUXURY production presentation',()=>{
it('renders elegant semantic structure without API access',()=>{const f=vi.spyOn(globalThis,'fetch');render(<LuxuryTemplate {...basicFixture({templateKey:'LUXURY'})}/>);expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);expect(screen.getByRole('banner')).toBeTruthy();expect(screen.getByRole('main')).toBeTruthy();expect(screen.getByRole('contentinfo')).toBeTruthy();expect(f).not.toHaveBeenCalled()});
it('keeps engine order and hides empty sections',()=>{const list=[s('SERVICES',{}),s('HERO',{}),s('ABOUT',{narrativeOverride:'Supplied'})];const before=JSON.stringify(list);const{container}=render(<LuxuryTemplate {...basicFixture({templateKey:'LUXURY',visibleSections:list,canonicalServices:[]})}/>);expect([...container.querySelectorAll('section')].map(x=>x.dataset.sectionType)).toEqual(['HERO','ABOUT']);expect(JSON.stringify(list)).toBe(before)});
it('uses refined services, process and invitation CTA treatments',()=>{render(<LuxuryTemplate {...basicFixture({templateKey:'LUXURY',visibleSections:[s('SERVICES',{}),s('DESIGN_PROCESS',{steps:[{step:'01',title:'Supplied step',desc:'Supplied detail'}]}),s('CTA',{headline:'Supplied invitation',description:'Supplied copy',buttonText:'Begin a conversation',buttonLink:'#contact'}),s('CONTACT',{contactIntro:'Supplied contact'})]})}/>);expect(screen.getByRole('heading',{name:'Made for how you live'})).toBeTruthy();expect(screen.getByRole('heading',{name:'Supplied step'})).toBeTruthy();expect(screen.getByRole('heading',{name:'Supplied invitation'})).toBeTruthy()});
it('handles absent projects, media, testimonials, awards, press, team and socials',()=>{const{container}=render(<LuxuryTemplate {...basicFixture({templateKey:'LUXURY',visibleSections:[s('FEATURED_PROJECTS',{projectIds:['future']}),s('PROJECT_GRID',{}),s('TESTIMONIALS',{items:[]}),s('AWARDS',{items:[]}),s('PRESS',{articles:[]}),s('TEAM',{members:[]}),s('BEFORE_AFTER',{}),s('VIDEO',{}),s('CONTACT',{}),s('CUSTOM_NOTE',{})],publicContacts:[],canonicalServices:[],canonicalServiceAreas:[]})}/>);expect(container.querySelectorAll('section')).toHaveLength(1);expect(container.textContent).not.toMatch(/undefined|TODO|Verified/)})
it('supports keyboard menu close and renders only supplied public contacts',()=>{render(<LuxuryTemplate {...basicFixture({templateKey:'LUXURY',visibleSections:[s('CONTACT',{contactIntro:'Contact'})],publicContacts:[{kind:'EMAIL',contactValue:'public@example.com'},{kind:'INSTAGRAM',contactValue:'javascript:alert(1)'}]})}/>);const menu=screen.getByRole('button',{name:'Menu'});fireEvent.click(menu);fireEvent.keyDown(menu,{key:'Escape'});expect(menu.getAttribute('aria-expanded')).toBe('false');expect(document.activeElement).toBe(menu);expect(screen.getByRole('link',{name:'public@example.com'})).toBeTruthy();expect(screen.queryByRole('link',{name:'Instagram'})).toBeNull()});
it('labels AI concepts and real results without fake media',()=>{render(<LuxuryTemplate {...basicFixture({templateKey:'LUXURY',visibleSections:[s('BEFORE_AI_REALITY',{pairs:[{conceptImageUrl:'https://example.com/concept.jpg',realityImageUrl:'https://example.com/result.jpg',title:'Supplied work'}]})]})}/>);expect(screen.getByText('AI Concept Visualization')).toBeTruthy();expect(screen.getByText('Real Result')).toBeTruthy()});
it('supports long content and server rendering',()=>{const long='Long luxury practice name '.repeat(16);expect(renderToString(<LuxuryTemplate {...basicFixture({templateKey:'LUXURY',studioName:long,headline:long})}/>)).toContain(long)});
it('rejects unsafe links and preserves future-theme isolation',()=>{for(const u of['javascript:alert(1)','data:text/html,x','file:///x','https://user:pass@example.com','#missing'])expect(safeUrl(u)).toBeUndefined();expect(TEMPLATE_REGISTRY.BASIC.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.MODERN.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.ARCHITECTURAL.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.WARM_NATURAL.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.DARK_CINEMATIC.status).toBe('AVAILABLE')});
it('has no API/auth/storage imports or unsafe raw HTML',()=>{const fs=require('node:fs');const path=require('node:path');for(const file of fs.readdirSync(path.resolve('src/components/portfolio/templates/luxury')).filter((x:string)=>/\.[tj]sx?$/.test(x))){const source=fs.readFileSync(path.resolve('src/components/portfolio/templates/luxury',file),'utf8');expect(source).not.toMatch(/apiFetch|AuthContext|fetch\(|localStorage|sessionStorage|dangerouslySetInnerHTML|\/lib\/auth/)}});
});


