import React from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { renderToString } from 'react-dom/server';
import { ModernTemplate } from '../portfolio/templates/modern/ModernTemplate';
import { basicFixture } from './BasicTemplate.fixture';
import { safeUrl, themeStyle } from '../portfolio/templates/modern/modern';
import type { PreviewSectionDto } from '@/lib/portfolio/types';
import { TEMPLATE_REGISTRY } from '@/lib/portfolio/template-registry';

afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const s=(type:PreviewSectionDto['sectionType'],content:Record<string,unknown>):PreviewSectionDto=>({sectionId:type,sectionType:type,displayOrder:1,schemaVersion:1,content});
describe('MODERN production presentation',()=>{
  it('renders a distinct modern landmark structure and never calls the API',()=>{const fetchSpy=vi.spyOn(globalThis,'fetch');render(<ModernTemplate {...basicFixture({templateKey:'MODERN'})}/>);expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);expect(screen.getByRole('banner')).toBeTruthy();expect(screen.getByRole('main')).toBeTruthy();expect(screen.getByRole('contentinfo')).toBeTruthy();expect(screen.getAllByText('Form & Field').length).toBeGreaterThan(0);expect(fetchSpy).not.toHaveBeenCalled();});
  it('keeps engine ordering and omits empty sections without mutation',()=>{const sections=[s('SERVICES',{}),s('HERO',{}),s('ABOUT',{narrativeOverride:'Supplied about'})];const before=JSON.stringify(sections);const {container}=render(<ModernTemplate {...basicFixture({templateKey:'MODERN',visibleSections:sections,canonicalServices:[]})}/>);expect([...container.querySelectorAll('section')].map(x=>x.dataset.sectionType)).toEqual(['HERO','ABOUT']);expect(JSON.stringify(sections)).toBe(before);});
  it('uses modern-specific service rows, process timeline and large CTA',()=>{render(<ModernTemplate {...basicFixture({templateKey:'MODERN',visibleSections:[s('SERVICES',{}),s('DESIGN_PROCESS',{steps:[{step:'A',title:'Supplied step',desc:'Supplied detail'}]}),s('CTA',{headline:'Supplied CTA',description:'Supplied copy',buttonText:'Start a conversation',buttonLink:'#contact'}),s('CONTACT',{contactIntro:'Supplied contact'})]})}/>);expect(screen.getByRole('heading',{name:'What we do'})).toBeTruthy();expect(screen.getByRole('heading',{name:'Supplied step'})).toBeTruthy();expect(screen.getByRole('heading',{name:'Supplied CTA'})).toBeTruthy();});
  it('supports empty projects/media/testimonials/awards/press/team/socials safely',()=>{const {container}=render(<ModernTemplate {...basicFixture({templateKey:'MODERN',visibleSections:[s('FEATURED_PROJECTS',{projectIds:['future']}),s('PROJECT_GRID',{}),s('TESTIMONIALS',{items:[]}),s('AWARDS',{items:[]}),s('PRESS',{articles:[]}),s('TEAM',{members:[]}),s('BEFORE_AFTER',{}),s('VIDEO',{}),s('CONTACT',{}),s('CUSTOM_NOTE',{})],publicContacts:[],canonicalServices:[],canonicalServiceAreas:[]})}/>);expect(container.querySelectorAll('section')).toHaveLength(1);expect(container.textContent).not.toMatch(/undefined|TODO|Verified/);});
  it('filters navigation to rendered sections and supports mobile Escape behavior',()=>{render(<ModernTemplate {...basicFixture({templateKey:'MODERN'})}/>);const menu=screen.getByRole('button',{name:/Index/});fireEvent.click(menu);expect(menu.getAttribute('aria-expanded')).toBe('true');expect(screen.getByRole('navigation')).toBeTruthy();fireEvent.keyDown(menu,{key:'Escape'});expect(menu.getAttribute('aria-expanded')).toBe('false');expect(document.activeElement).toBe(menu);});
  it('renders only privacy-filtered valid contact actions',()=>{render(<ModernTemplate {...basicFixture({templateKey:'MODERN',publicContacts:[{kind:'EMAIL',contactValue:'public@example.com'},{kind:'PHONE',contactValue:'+91 12345 67890'},{kind:'INSTAGRAM',contactValue:'javascript:alert(1)'}],visibleSections:[s('CONTACT',{contactIntro:'Contact'})]})}/>);expect(screen.getByRole('link',{name:'public@example.com'})).toBeTruthy();expect(screen.getByRole('link',{name:'+91 12345 67890'})).toBeTruthy();expect(screen.queryByRole('link',{name:'Instagram'})).toBeNull();});
  it('renders explicit AI labels and supplied media only',()=>{render(<ModernTemplate {...basicFixture({templateKey:'MODERN',visibleSections:[s('BEFORE_AI_REALITY',{pairs:[{conceptImageUrl:'https://example.com/concept.jpg',realityImageUrl:'https://example.com/result.jpg',title:'Supplied work'}]})]})}/>);expect(screen.getByText('AI Concept Visualization')).toBeTruthy();expect(screen.getByText('Real Result')).toBeTruthy();});
  it('supports long content at server render without browser globals',()=>{const long='Long practice name '.repeat(20);expect(renderToString(<ModernTemplate {...basicFixture({templateKey:'MODERN',studioName:long,headline:long})}/>)).toContain(long);});
  it('rejects unsafe URLs and uses controlled theme values',()=>{for(const u of ['javascript:alert(1)','data:text/html,x','file:///x','https://user:pass@example.com','#missing'])expect(safeUrl(u)).toBeUndefined();expect(JSON.stringify(themeStyle(basicFixture({primaryColor:'red; background:url(evil)'})))).not.toContain('evil');});
it('keeps completed themes available while future themes stay scaffolded',()=>{expect(TEMPLATE_REGISTRY.MODERN.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.MODERN.isSelectable).toBe(true);expect(TEMPLATE_REGISTRY.BASIC.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.LUXURY.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.ARCHITECTURAL.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.ARCHITECTURAL.isSelectable).toBe(true);expect(TEMPLATE_REGISTRY.WARM_NATURAL.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.WARM_NATURAL.isSelectable).toBe(true);expect(TEMPLATE_REGISTRY.DARK_CINEMATIC.status).toBe('AVAILABLE');expect(TEMPLATE_REGISTRY.DARK_CINEMATIC.isSelectable).toBe(true);});
  it('has no API/auth/storage boundary imports or unsafe HTML',()=>{const fs=require('node:fs');const path=require('node:path');for(const file of fs.readdirSync(path.resolve('src/components/portfolio/templates/modern')).filter((x:string)=>/\.[tj]sx?$/.test(x))){const source=fs.readFileSync(path.resolve('src/components/portfolio/templates/modern',file),'utf8');expect(source).not.toMatch(/apiFetch|AuthContext|fetch\(|localStorage|sessionStorage|dangerouslySetInnerHTML|\/lib\/auth/);}});
});


