import React from 'react';
import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {PortfolioGallery,GalleryPhoto,gallerySource} from '../portfolio/gallery/PortfolioGallery';
beforeEach(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};});
afterEach(cleanup);
const folders=[{id:'k',name:'Kitchens',photos:[{id:'1',src:'https://example.com/1.jpg',alt:'First room'},{id:'2',src:'https://example.com/2.jpg',alt:'Second room',kind:'AI_CONCEPT'}]},{id:'b',name:'Bedrooms',photos:[{id:'3',src:'https://example.com/3.jpg',alt:'Bedroom'}]}];
describe('Portfolio gallery',()=>{
 it('opens folders, moves with arrows and switches folders without losing disclosure',()=>{render(<PortfolioGallery folders={folders}/>);fireEvent.click(screen.getByRole('button',{name:/Kitchens/}));const dialog=screen.getByRole('dialog');expect(dialog).toBeTruthy();fireEvent.keyDown(dialog,{key:'ArrowRight'});expect(screen.getByText('AI concept visualization')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Contact sheet'}));fireEvent.click(screen.getByRole('button',{name:'View photo 1'}));expect(screen.getByText('01 / 02')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Bedrooms, 1 photo'}));expect(screen.getByText('01 / 01')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Close gallery'}));expect(screen.queryByRole('dialog')).toBeNull();expect(document.body.style.overflow).not.toBe('hidden');});
 it('opens existing template photos with a keyboard accessible button',()=>{render(<main><section><h2>Spaces</h2><article><h3>Project one</h3><figure><GalleryPhoto src="https://example.com/a.jpg" alt="Living room"/><figcaption>After</figcaption></figure></article></section></main>);fireEvent.click(screen.getByRole('button',{name:'Open photo: Living room'}));expect(screen.getByRole('dialog')).toBeTruthy();expect(screen.getAllByText('Project one').length).toBeGreaterThan(0);fireEvent(screen.getByRole('dialog'),new Event('cancel',{cancelable:true}));expect(screen.queryByRole('dialog')).toBeNull();});
 it('rejects unsafe and private media paths',()=>{for(const s of ['javascript:alert(1)','data:image/png,x','https://user:pass@example.com/a','/api/v1/media/private/a','//evil.test/a'])expect(gallerySource(s)).toBeUndefined();expect(gallerySource('/api/v1/media/public/a')).toBeTruthy();render(<PortfolioGallery folders={[{id:'bad',name:'Hidden',photos:[{id:'1',src:'javascript:bad'}]}]}/>);expect(screen.queryByRole('region')).toBeNull();});
});
