package com.interior.platform.notifications.domain;

public enum NotificationType {
    NEW_LEAD,
    LEAD_FOLLOW_UP,
    NEW_REVIEW,
    REVIEW_RESPONSE,
    VERIFICATION_UPDATE,
    AI_GENERATION_COMPLETE,
    AI_GENERATION_FAILED,
    CLIENT_APPROVED_CONCEPT,
    CLIENT_REQUESTED_CHANGES,
    PORTFOLIO_PUBLISHED,
    PORTFOLIO_ACTION_REQUIRED,
    PROJECT_ACTION_REQUIRED,
    STUDIO_INVITATION_ACCEPTED,
    STUDIO_MEMBER_ADDED,
    STUDIO_ROLE_CHANGED,
    STUDIO_MEMBER_REMOVED,
    SYSTEM_NOTICE
}
