'use client';
/* eslint-disable @next/next/no-img-element -- existing media derivatives. */
import {useEffect,useState} from 'react';
import {Dialog} from '@/components/overlay/Dialog';
import {fetchGalleryFolders,saveGalleryFolder,type StoredFolder} from '@/lib/media/gallery-api';
import type {MediaDetailResponse} from '@/lib/media/types';
import {PortfolioGallery,type GalleryFolder,gallerySource} from '@/components/portfolio/gallery/PortfolioGallery';
import styles from './GalleryFolderManager.module.css';

const empty:Omit<StoredFolder,'id'>={name:'',description:'',published:false,version:0,mediaIds:[]};
export function GalleryFolderManager({media,projects}:{media:MediaDetailResponse[];projects:{id:string;title:string}[]}){
  const [folders,setFolders]=useState<StoredFolder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [editing,setEditing]=useState<StoredFolder|Omit<StoredFolder,'id'>|null>(null),[saving,setSaving]=useState(false),[search,setSearch]=useState(''),[preview,setPreview]=useState(false);
  async function load(){setLoading(true);try{setFolders(await fetchGalleryFolders());setError('');}catch{setError('Folders could not be loaded. Try again.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  function source(m:MediaDetailResponse){return m.derivatives.find(d=>d.variantName==='LARGE')?.publicUrl||m.derivatives[0]?.publicUrl||'';}
  const available=media.filter(m=>m.processingStatus==='READY');
  const previews:GalleryFolder[]=folders.map(f=>({id:f.id,name:f.name,description:f.description,photos:f.mediaIds.flatMap(id=>{const m=media.find(m=>m.id===id);return m&&gallerySource(source(m))?[{id:m.id,src:source(m),alt:m.altText,caption:m.caption,kind:m.mediaType}]:[];})}));
  async function save(){if(!editing||saving)return;setSaving(true);setError('');try{const result=await saveGalleryFolder(editing,'id'in editing?editing.id:undefined);setFolders(items=>[...items.filter(f=>f.id!==result.id),result]);setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Folder could not be saved. Your changes are still here.');}finally{setSaving(false);}}
  return <section className={styles.manager} aria-label="Custom gallery folders"><header><div><span>YOUR PORTFOLIO, CURATED</span><h2>Gallery folders</h2><p>Group photographs from any project. One photo can belong to several folders.</p></div><div className={styles.actions}><button type="button" onClick={()=>setPreview(v=>!v)}>{preview?'Hide preview':'Preview gallery'}</button><button type="button" onClick={()=>{setEditing({...empty,mediaIds:[]});setSearch('');setError('');}}>+ New folder</button></div></header>
    {loading?<p role="status">Loading folders…</p>:error&&!editing?<p role="alert">{error} <button type="button" onClick={load}>Try again</button></p>:!folders.length?<div className={styles.empty}><h3>A place for every detail.</h3><p>Create your first folder—Kitchens, Bedrooms, Materials, or a collection of your own.</p></div>:<div className={styles.cards}>{folders.map(f=>{const cover=previews.find(p=>p.id===f.id)?.photos[0];return <button type="button" key={f.id} onClick={()=>{setEditing({...f,mediaIds:[...f.mediaIds]});setSearch('');setError('');}}>{cover?<img src={cover.src} alt=""/>:<div className={styles.blank}>No photos yet</div>}<div><strong>{f.name}</strong><small>{f.mediaIds.length} photos · {f.published?'Published':'Draft'}</small><span>Edit folder ↗</span></div></button>;})}</div>}
    {preview&&<PortfolioGallery folders={previews}/>}
    <Dialog isOpen={!!editing} onClose={()=>{if(!saving)setEditing(null);}} title={editing&&'id'in editing?'Edit gallery folder':'Create gallery folder'} description="Choose photos from across your projects. Removing a photo here keeps the original in its project." maxWidth="full">
    {editing&&<form className={styles.form} onSubmit={e=>{e.preventDefault();void save();}}><label>Folder name<input required maxLength={80} value={editing.name} placeholder="For example, Kitchens" onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Description<textarea maxLength={500} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label className={styles.check}><input type="checkbox" checked={editing.published} onChange={e=>setEditing({...editing,published:e.target.checked})}/>Publish folder on my portfolio</label><p>Only ready, public-eligible photos from published projects appear to visitors. Private photos stay private.</p>
    <label>Find photos<input type="search" placeholder="Search by project or caption" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className={styles.selection} aria-label="Choose folder photos">{available.filter(m=>`${m.altText||''} ${m.caption||''} ${projects.find(p=>p.id===m.projectId)?.title||''}`.toLowerCase().includes(search.toLowerCase())).map(m=><label key={m.id}><input type="checkbox" checked={editing.mediaIds.includes(m.id)} onChange={e=>setEditing({...editing,mediaIds:e.target.checked?[...editing.mediaIds,m.id]:editing.mediaIds.filter(id=>id!==m.id)})}/>{gallerySource(source(m))?<img src={source(m)} alt={m.altText||'Project photo'}/>:<div className={styles.blank}>Preview unavailable</div>}<span>{m.caption||m.altText||projects.find(p=>p.id===m.projectId)?.title||'Project photo'}<small>{m.mediaType==='AI_CONCEPT'?'AI concept · ':''}{m.visibility==='PRIVATE'?'Private':m.mediaTypeDisplayName}</small></span></label>)}</div>{!available.length&&<p>Upload and process photos in a project first, then add them here.</p>}
    <div className={styles.order}><strong>Folder order · {editing.mediaIds.length}/200 photos</strong>{editing.mediaIds.map((id,i)=><div key={id}><span>{i+1}. {media.find(m=>m.id===id)?.caption||media.find(m=>m.id===id)?.altText||'Project photo'}</span><button type="button" disabled={i===0} aria-label={`Move photo ${i+1} earlier`} onClick={()=>{const ids=[...editing.mediaIds];[ids[i-1],ids[i]]=[ids[i],ids[i-1]];setEditing({...editing,mediaIds:ids});}}>↑</button><button type="button" aria-label={`Remove photo ${i+1} from folder`} onClick={()=>setEditing({...editing,mediaIds:editing.mediaIds.filter(x=>x!==id)})}>Remove</button></div>)}</div>
    {error&&<p role="alert">{error}</p>}<div className={styles.actions}><button type="button" disabled={saving} onClick={()=>setEditing(null)}>Cancel</button><button type="submit" disabled={saving||!editing.name.trim()||editing.mediaIds.length>200}>{saving?'Saving…':'Save folder'}</button></div></form>}
    </Dialog>
  </section>;
}
