package com.interior.platform.reviews.web;

import com.interior.platform.reviews.domain.StudioReviewRecord;
import com.interior.platform.reviews.dto.*;
import com.interior.platform.reviews.service.ReviewInvitationService;
import com.interior.platform.reviews.service.ReviewService;
import com.interior.platform.security.domain.ActorContext;
import com.interior.platform.security.interceptor.SecurityInterceptor;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping
@Tag(name = "Studio Reviews CRM", description = "Endpoints for professional studio review invitation issuance, listing, and single public responses")
public class StudioReviewController {

    private final ReviewInvitationService invitationService;
    private final ReviewService reviewService;

    public StudioReviewController(ReviewInvitationService invitationService, ReviewService reviewService) {
        this.invitationService = invitationService;
        this.reviewService = reviewService;
    }

    @PostMapping("/leads/{leadId}/review-invitations")
    @Operation(summary = "Generate client review invitation", description = "Generates a 256-bit cryptographically secure review invitation link for a WON lead.")
    public ResponseEntity<CreateReviewInvitationResponse> createInvitation(
            HttpServletRequest request,
            @PathVariable("leadId") UUID leadId,
            @RequestBody(required = false) CreateReviewInvitationRequest body,
            @RequestHeader(value = "X-Studio-Id", required = false) String studioIdHeader,
            @RequestParam(value = "studioId", required = false) UUID studioIdParam
    ) {
        ActorContext actor = extractActor(request);
        UUID studioId = resolveRequestedStudioId(studioIdHeader, studioIdParam, actor);

        UUID projectId = body != null ? body.projectId() : null;
        CreateReviewInvitationRequest req = new CreateReviewInvitationRequest(leadId, projectId);

        CreateReviewInvitationResponse response = invitationService.createInvitation(actor, studioId, req);

        return ResponseEntity.status(HttpStatus.CREATED)
                .header(HttpHeaders.CACHE_CONTROL, "private, no-store, max-age=0, must-revalidate")
                .header(HttpHeaders.PRAGMA, "no-cache")
                .body(response);
    }

    @GetMapping("/reviews/invitations")
    @Operation(summary = "List review invitations", description = "Lists review invitations generated by the studio.")
    public ResponseEntity<List<ReviewInvitationDto>> listInvitations(
            HttpServletRequest request,
            @RequestHeader(value = "X-Studio-Id", required = false) String studioIdHeader,
            @RequestParam(value = "studioId", required = false) UUID studioIdParam,
            @RequestParam(value = "limit", required = false, defaultValue = "50") int limit,
            @RequestParam(value = "offset", required = false, defaultValue = "0") int offset
    ) {
        ActorContext actor = extractActor(request);
        UUID studioId = resolveRequestedStudioId(studioIdHeader, studioIdParam, actor);

        List<ReviewInvitationDto> list = invitationService.listInvitations(actor, studioId, limit, offset);
        return ResponseEntity.ok(list);
    }

    @PostMapping("/reviews/invitations/{id}/revoke")
    @Operation(summary = "Revoke review invitation", description = "Revokes an active review invitation and immediately invalidates any active sessions.")
    public ResponseEntity<Void> revokeInvitation(
            HttpServletRequest request,
            @PathVariable("id") UUID invitationId,
            @RequestHeader(value = "X-Studio-Id", required = false) String studioIdHeader,
            @RequestParam(value = "studioId", required = false) UUID studioIdParam
    ) {
        ActorContext actor = extractActor(request);
        UUID studioId = resolveRequestedStudioId(studioIdHeader, studioIdParam, actor);

        invitationService.revokeInvitation(actor, studioId, invitationId);
        return ResponseEntity.noContent().build();
    }

    @GetMapping("/reviews/studio")
    @Operation(summary = "List studio reviews for workspace", description = "Lists all client reviews for the authenticated studio.")
    public ResponseEntity<List<StudioReviewRecord>> listStudioReviews(
            HttpServletRequest request,
            @RequestHeader(value = "X-Studio-Id", required = false) String studioIdHeader,
            @RequestParam(value = "studioId", required = false) UUID studioIdParam,
            @RequestParam(value = "limit", required = false, defaultValue = "50") int limit,
            @RequestParam(value = "offset", required = false, defaultValue = "0") int offset
    ) {
        ActorContext actor = extractActor(request);
        UUID studioId = resolveRequestedStudioId(studioIdHeader, studioIdParam, actor);

        List<StudioReviewRecord> list = reviewService.listStudioReviews(actor, studioId, limit, offset);
        return ResponseEntity.ok(list);
    }

    @PostMapping("/reviews/{id}/response")
    @Operation(summary = "Post single studio response to review", description = "Allows professional studio to post or edit a single public response to a client review.")
    public ResponseEntity<Void> respondToReview(
            HttpServletRequest request,
            @PathVariable("id") UUID reviewId,
            @Valid @RequestBody StudioReviewResponseRequest req,
            @RequestHeader(value = "X-Studio-Id", required = false) String studioIdHeader,
            @RequestParam(value = "studioId", required = false) UUID studioIdParam
    ) {
        ActorContext actor = extractActor(request);
        UUID studioId = resolveRequestedStudioId(studioIdHeader, studioIdParam, actor);

        reviewService.respondToReview(actor, studioId, reviewId, req);
        return ResponseEntity.noContent().build();
    }

    private ActorContext extractActor(HttpServletRequest request) {
        ActorContext actor = (ActorContext) request.getAttribute(SecurityInterceptor.ACTOR_ATTRIBUTE);
        return actor != null ? actor : ActorContext.anonymous();
    }

    private UUID resolveRequestedStudioId(String header, UUID param, ActorContext actor) {
        if (param != null) return param;
        if (header != null && !header.isBlank()) {
            try {
                return UUID.fromString(header.trim());
            } catch (IllegalArgumentException ignored) {
            }
        }
        if (actor != null && actor.activeStudioId() != null) {
            return actor.activeStudioId();
        }
        return null;
    }
}
